name: My First CI

on:
  push:

jobs:
  inspect-website:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Show repository files
        run: ls -la

      - name: Check index.html exists
        run: test -f index.html
